# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1025, 732)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnSelectImage = QtWidgets.QPushButton(self.centralwidget)
        self.btnSelectImage.setGeometry(QtCore.QRect(60, 90, 93, 28))
        self.btnSelectImage.setObjectName("btnSelectImage")
        self.btnCancle = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancle.setGeometry(QtCore.QRect(60, 170, 93, 28))
        self.btnCancle.setObjectName("btnCancle")
        self.btnDaoAnh = QtWidgets.QPushButton(self.centralwidget)
        self.btnDaoAnh.setGeometry(QtCore.QRect(60, 240, 93, 28))
        self.btnDaoAnh.setObjectName("btnDaoAnh")
        self.btnContast = QtWidgets.QPushButton(self.centralwidget)
        self.btnContast.setGeometry(QtCore.QRect(60, 310, 93, 28))
        self.btnContast.setObjectName("btnContast")
        self.btnGamma = QtWidgets.QPushButton(self.centralwidget)
        self.btnGamma.setGeometry(QtCore.QRect(60, 390, 93, 28))
        self.btnGamma.setObjectName("btnGamma")
        self.btnTrungvi = QtWidgets.QPushButton(self.centralwidget)
        self.btnTrungvi.setGeometry(QtCore.QRect(60, 460, 93, 28))
        self.btnTrungvi.setObjectName("btnTrungvi")
        self.lbImage = QtWidgets.QLabel(self.centralwidget)
        self.lbImage.setGeometry(QtCore.QRect(390, 80, 531, 441))
        self.lbImage.setObjectName("lbImage")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1025, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnSelectImage.setText(_translate("MainWindow", "Select Images"))
        self.btnCancle.setText(_translate("MainWindow", "Cancle"))
        self.btnDaoAnh.setText(_translate("MainWindow", "Đảo ảnh"))
        self.btnContast.setText(_translate("MainWindow", "Contast"))
        self.btnGamma.setText(_translate("MainWindow", "Gamma"))
        self.btnTrungvi.setText(_translate("MainWindow", "Trung vi"))
        self.lbImage.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
